### PR TITLE
Plone ve i18n support merge support

### PR DESCRIPTION
**Pull request by ichim-david**

### CODE REVIEW

**Comment by ichim-david** [comment]
@macagua  I don't understand how volto starts for you
https://ci.eionet.europa.eu/job/volto-addons/job/volto-accordion-block/job/plone-ve-i18n_support/1/pipeline-console/?start-byte=1238845&selected-node=31#log-1375
eslint-warnings
volto-start-error
You can't call useInt() hook in extendSchema as jslint clearly complains about
  24:16  error  React Hook "useIntl" is called in function "extendedSchema" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter  react-hooks/rules-of-hooks
You need to find another way to pass the intl object so that volto starts, push to your fork and then I can try again to update this local pull request and see if everything starts and runs fine

**Comment by macagua** [comment]
@ichim-david I can't access to https://ci.eionet.europa.eu/job/volto-addons/job/volto-accordion-block/job/plone-ve-i18n_support/1/pipeline-console/?start-byte=1238845&selected-node=31#log-1375

screenshot-ci eionet europa eu-2023 08 25-06_12_50

**Comment by ichim-david** [comment]
> @ichim-david I can't access to https://ci.eionet.europa.eu/job/volto-addons/job/volto-accordion-block/job/plone-ve-i18n_support/1/pipeline-console/?start-byte=1238845&selected-node=31#log-1375
> 
> screenshot-ci eionet europa eu-2023 08 25-06_12_50

This is why I've attached the screenshots with the relevant eslint warnings in case you couldn't access the link, there is nothing more interesting out of that test run besides what I've given you as screenshots and written feedback

**Comment by macagua** [comment]
> > @ichim-david I can't access to https://ci.eionet.europa.eu/job/volto-addons/job/volto-accordion-block/job/plone-ve-i18n_support/1/pipeline-console/?start-byte=1238845&selected-node=31#log-1375
> > screenshot-ci eionet europa eu-2023 08 25-06_12_50
> 
> @macagua This is why I've attached the screenshots with the relevant eslint warnings in case you couldn't access the link, there is nothing more interesting out of that test run besides what I've given you as screenshots and written feedback

@ichim-david Fixed on commit [fe02ffd]

**Comment by ichim-david** [comment]
@macagua  the duplicate is nothing ..the intl part is the big issues that prevents volto from compiling and starting, you have to try yourself

**Comment by macagua** [comment]
> @macagua the duplicate is nothing ..the intl part is the big issues that prevents volto from compiling and starting, you have to try yourself

@ichim-david let me check, just one question, can you tell me how do you run the test with jslint? because in the DEVELOP file, don't have any reference to with jslint (I am following these instructions), in this case I used the 'prettier' package QA test to fix any warnings...

**Comment by ichim-david** [comment]
@macagua  always look at the scripts defined in package.json
although I admit it's not a very straightforward name (lint vs eslint) indeed but it's here
https://github.com/eea/volto-accordion-block/blob/master/package.json#L43
https://github.com/eea/volto-accordion-block/blob/master/Makefile#L120
so run run in the package root:
make lint-fix

**Comment by macagua** [comment]
> @macagua always look at the scripts defined in package.json although I admit it's not a very straightforward name (lint vs eslint) indeed but it's here https://github.com/eea/volto-accordion-block/blob/master/package.json#L43 https://github.com/eea/volto-accordion-block/blob/master/Makefile#L120 so run run in the package root: make lint-fix

@ichim-david Ok I am installing the eslint for to review that reported the ``make lint-fix`` command

**Comment by ichim-david** [comment]
@macagua get in touch with me within the plone discord if you need to signal something to me
you will find me if you search for: ichim-david

**Comment by ichim-david** [comment]
@macagua  for reference these are the files that I needed to change in order to get volto to start
https://gist.github.com/ichim-david/bfd8c344e51f886b08977c58c53892ee
On non React class or function based components you need to use createIntl
as described in https://formatjs.io/docs/react-intl/api#createintl

I don't know if the messages still end up in the i18n locales and are read, for you to find out

**Comment by macagua** [comment]
> @macagua I don't understand how volto starts for you https://ci.eionet.europa.eu/job/volto-addons/job/volto-accordion-block/job/plone-ve-i18n_support/1/pipeline-console/?start-byte=1238845&selected-node=31#log-1375 eslint-warnings volto-start-error You can't call useInt() hook in extendSchema as jslint clearly complains about 24:16 error React Hook "useIntl" is called in function "extendedSchema" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter react-hooks/rules-of-hooks You need to find another way to pass the intl object so that volto starts, push to your fork and then I can try again to update this local pull request and see if everything starts and runs fine

@ichim-david Fixed with commit [666bcb8]

**Pull request merged**
