### PR TITLE
Add infrastructure support for i18n and locales folder

### PR DESCRIPTION
**Pull request by sneridagh**

### CODE REVIEW

**Review by avoinea — APPROVED** [review]

**Comment by tisto** [comment]
@avoinea @tiberiuichim can you give me access to this repo as well? I'd like to add the German translations for this block.

**Comment by avoinea** [comment]
@tisto Done.

**Comment by avoinea** [comment]
@sneridagh @tisto Is this ready for merge? Or you want to add more languages?

**Comment by tisto** [comment]
@avoinea ready for merge and release!

**Pull request merged**
